import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "@/shared/styles/global.css";
import { QueryProvider } from "@/shared/providers/QueryProvider";

const pretendard = localFont({
  src: "../shared/assets/font/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Shareit!",
  // description: "Generated by create next app",
};

// safe-area-inset-*(env())이 실제 값을 갖도록 노치 영역까지 뷰포트를 확장합니다.
export const viewport: Viewport = {
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className="min-h-dvh bg-primary-100">
        {/* 데스크탑·태블릿에서도 모바일 폭(480px)으로 중앙 고정. transform-gpu로 내부 fixed(탭바·오버레이)를 프레임 안에 가둔다. */}
        <div className="mx-auto flex min-h-dvh w-full max-w-120 flex-col bg-background transform-gpu">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
