import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "@/shared/styles/global.css";

const pretendard = localFont({
  src: "../shared/assets/font/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// safe-area-inset-*(env())이 실제 값을 갖도록 노치 영역까지 뷰포트를 확장합니다.
export const viewport: Viewport = {
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
